---
info:
  title: BlackMarlinExec
  description: Enenumerate, attack, or poisoning target inside networks
  x-cortex-git:
    github:
      alias: byt3n33dl3
      repository: byt3n33dl3/BlackMarlinExec
  x-cortex-tag: BlackMarlinExec
  x-cortex-type: service
  x-cortex-domain-parents: hosts
  - tag: BME
openapi: 2.2.0
servers:
- url: "/"
