# Reference: https://build-cpp.github.io/cmkr/cmake-toml

[options]
INSTALL_GTEST = false
BUILD_GMOCK = false
BENCHMARK_ENABLE_TESTING = false
BENCHMARK_ENABLE_INSTALL = false
BENCHMARK_USE_BUNDLED_GTEST = false

[fetch-content.Zydis]
git = "https://github.com/zyantific/zydis"
tag = "v4.1.0"
system = true

[fetch-content.GTest]
condition = "build-tests"
git = "https://github.com/google/googletest"
tag = "release-1.11.0"
system = true

[fetch-content.GBenchmark]
condition = "build-benchmarks"
git = "https://github.com/google/benchmark"
tag = "v1.6.1"
system = true